### ISSUE TITLE
R requirement

### ISSUE THREAD

**Issue by user06-stephan-majda** [tbenavi1/smudgeplot#20]
Hello,

I just got the error:
"unused argument (left.open = T)" of the R command _findInterval_
this option was added in R version 3.3.2
I suggest checking the R version in the install process.

After updating R it works great. Thanks,
Stephan Majda

**Comment by KamilSJaron** [comment]
Hi Stephan,

good catch, thanks fixed in 74afa4ddefe71c73dfae256bbefca794cde60077. Once the package will be bit more mature I would like to place it to CRAN or Bioconductor, which would resolve this problems.
