### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by rotifergirl** [tbenavi1/smudgeplot#22]
When running Rscript install.R, I get some errors, here is the whole output as it is printed in stderr

> > Updating smudgeplot documentation
> Loading smudgeplot
> Loading required package: viridis
> Loading required package: viridisLite
> Loading required package: argparse
> Writing NAMESPACE
> Writing annotate_peaks.Rd
> Writing annotate_summits.Rd
> Writing estimate_1n_coverage_1d_subsets.Rd
> Writing estimate_1n_coverage_highest_peak.Rd
> Writing filter_peak_sizes.Rd
> Writing filter_peaks.Rd
> Writing generate_summary.Rd
> Writing get_1d_peaks.Rd
> Writing get_default_col_ramp.Rd
> Writing get_peak_sizes.Rd
> Writing get_peak_summary.Rd
> Writing get_smudge_container.Rd
> Writing get_trinoploid_1n_est.Rd
> Writing guess_genome_structure.Rd
> Writing peak_agregation.Rd
> Writing plot_expected_haplotype_structure.Rd
> Writing plot_histograms.Rd
> Writing plot_legend.Rd
> Writing plot_seq_error_line.Rd
> Writing plot_smudgeplot.Rd
> Writing round_minor_variant_cov.Rd
> Writing rounding.Rd
> Writing smudge_summary.Rd
> Writing smudge_warn.Rd
> Writing transform_minor_variant_cov.Rd
> Writing transform_pair_cov.Rd
> Warning messages:
> 1: roxygen2 requires Encoding: UTF-8 
> 2: In .doLoadActions(where, attach) :
>   trying to execute load actions without 'methods' package
> Loading smudgeplot
> 
> Attaching package: ‘testthat’
> 
> The following objects are masked from ‘package:devtools’:
> 
>     setup, test_file
> 
> Testing smudgeplot
> ✔ | OK F W S | Context
> ✔ |  1       | 1d subsets fitting [0.1 s]
> ✖ |  0 1     | integration
> ────────────────────────────────────────────────────────────────────────────────
> test-fitting.R:17: error: (unknown)
> unused argument (left.open = T)
> 1: get_smudge_container(minor_variant_rel_cov, total_pair_cov, .nbins = nbins) at /users/jblommaert/smudgeplot/tests/testthat/test-fitting.R:17
> 2: as.data.frame(table(findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T), 
>        findInterval(.total_pair_cov, smudge_container$y, left.open = T)), stringsAsFactors = F) at /users/jblommaert/smudgeplot/R/get_smudge_container.R:17
> 3: table(findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T), findInterval(.total_pair_cov, 
>        smudge_container$y, left.open = T))
> 4: findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T)
> ────────────────────────────────────────────────────────────────────────────────
> ✖ |  0 1     | smudge container generation
> ────────────────────────────────────────────────────────────────────────────────
> test-get_smudge_container.R:6: error: (unknown)
> unused argument (left.open = T)
> 1: get_smudge_container(x, y, .nbins = 3, .xlim = c(0, 3), .ylim = c(0, 3)) at /users/jblommaert/smudgeplot/tests/testthat/test-get_smudge_container.R:6
> 2: as.data.frame(table(findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T), 
>        findInterval(.total_pair_cov, smudge_container$y, left.open = T)), stringsAsFactors = F) at /users/jblommaert/smudgeplot/R/get_smudge_container.R:17
> 3: table(findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T), findInterval(.total_pair_cov, 
>        smudge_container$y, left.open = T))
> 4: findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T)
> ────────────────────────────────────────────────────────────────────────────────
> ✖ |  0 1     | generation of peak summary
> ────────────────────────────────────────────────────────────────────────────────
> test-get_summary.R:17: error: (unknown)
> unused argument (left.open = T)
> 1: get_smudge_container(minor_variant_rel_cov, total_pair_cov, .nbins = nbins) at /users/jblommaert/smudgeplot/tests/testthat/test-get_summary.R:17
> 2: as.data.frame(table(findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T), 
>        findInterval(.total_pair_cov, smudge_container$y, left.open = T)), stringsAsFactors = F) at /users/jblommaert/smudgeplot/R/get_smudge_container.R:17
> 3: table(findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T), findInterval(.total_pair_cov, 
>        smudge_container$y, left.open = T))
> 4: findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T)
> ────────────────────────────────────────────────────────────────────────────────
> 
> ══ Results ═════════════════════════════════════════════════════════════════════
> Duration: 0.3 s
> 
> OK:       1
> Failed:   3
> Warnings: 0
> Skipped:  0
> Installing package into ‘/users/jblommaert/R/x86_64-pc-linux-gnu-library/3.2’
> (as ‘lib’ is unspecified)
> * installing *source* package ‘smudgeplot’ ...
> ** R
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded
> * DONE (smudgeplot)
>

**Comment by rotifergirl** [comment]
I believe this is leading to an error when I run the smudgeplot.R script:

> running	Smudgeplot v0.1.3
> 
> ######################
> ## INPUT PROCESSING ##
> ######################
> 
> #############
> ## SUMMARY ##
> #############
> Error in findInterval(.minor_variant_rel_cov, smudge_container$x, left.open = T) : 
>   unused argument (left.open = T)
> Calls: get_smudge_container -> as.data.frame -> table -> findInterval
> Execution halted
>

**Comment by KamilSJaron** [comment]
I see. It seems that you have an older version of R. The `(left.open = T)` was added in 3.2.0, so we need any R version newer than that. I think It's the same issue as the issue #20.

I am just surprised that install allowed you to proceed, because DESCRIPTION specifies the required version of R.

**Comment by KamilSJaron** [comment]
Ha, we need R version >3.3.2, not >3.2.0

TODO -> fix the description file

**Comment by KamilSJaron** [comment]
fixed in 2b8065fc1becc3ba9b056e14444a80fbddd3b3d4
